config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  resources :blog_posts

  # Defines the root path route ("/")
  # root "articles#index"
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
    
  def index
    @blog_posts = BlogPost.all
  end

    def show
    end

    def new
        @blog_post = BlogPost.new
    end

    def create

        @blog_post = BlogPost.new(blog_post_params)

        if @blog_post.save
            flash[:notice] = "Blog post was created successfully."
            redirect_to @blog_post
        else
            flash.now[:alert] = "Error creating blog post."
            render :new, status: :unprocessable_entity
        end
    end

    def edit
    end

    def update

        if @blog_post.update(blog_post_params)
            flash[:notice] = "Blog post was updated successfully."
            redirect_to @blog_post
        else
            flash.now[:alert] = "Error updating blog post."
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @blog_post.destroy
        flash[:notice] = "Blog post was deleted successfully."
        redirect_to blog_posts_path
    end


    private

    def blog_post_params
        params.require(:blog_post).permit(:title, :content)
    end


    def set_blog_post
        @blog_post = BlogPost.find(params[:id])
    rescue ActiveRecord::RecordNotFound
        flash[:alert] = "The blog post you're looking for cannot be found."
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |f| %>
<% if f.object.errors.any? %>
    <div id="error_explanation">
        <ul>
        <% f.object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
        </ul>
    </div>

<% end %>

<div>
  <%= f.label :title %>
  <%= f.text_field :title %>

  </div>

  <div>
      <%= f.label :content %>
      <%= f.text_area :content %>
  </div>

  <%= f.submit %>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render "form", blog_post: @blog_post %>

<p><%= link_to "Back to blog", blog_posts_path %></p>
<%= button_to "Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure? "}   %>

app/views/blog_posts/index.html.erb
    <h1>My Blog</h1>

        <div class="posts">
      <% @blog_posts.each do |blog_post| %>
    
            <h2><%= blog_post.title %></h2>
            <p><%= blog_post.content %></p>
            <p><%= link_to "Read more", blog_post_path(blog_post) %></p>

      <% end %>
      </div>

        <p><%= link_to "New Post", new_blog_post_path %></p>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render "form", blog_post: @blog_post %>

<p><%= link_to "Back to blog", blog_posts_path %></p>

app/views/blog_posts/show.html.erb
<div class="post">
    <h2><%= @blog_post.title %></h2>
    <p><%= @blog_post.content %></p>
    <p><%= link_to "Back to blog", blog_posts_path %></p>
    <p><%= link_to "Edit", edit_blog_post_path(@blog_post) %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">

     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

       <% if user_signed_in? %>
          <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: "bg-gray-100 px-4 py-4 rounded" %>
          <% else %>
          <%= button_to 'Sign in', new_user_session_path, class: "bg-gray-100 px-4 py-4 rounded" %>
        <% end %>
    <%= yield %>
  </body>
</html>